apiVersion: flows.netobserv.io/v1alpha1
kind: FlowCollector
metadata:
  name: cluster
spec:
  ipfix:
    cacheActiveTimeout: 60s
    cacheMaxFlows: 400
    sampling: 100
  goflowkube:
    kind: Deployment
    replicas: 1
    port: 2055
    image: 'quay.io/netobserv/goflow2-kube:latest'
    imagePullPolicy: IfNotPresent
    logLevel: info
  loki:
    url: 'http://loki:3100/'
    batchWait: 1s
    batchSize: 102400
    minBackoff: 1s
    maxBackoff: 300s
    maxRetries: 10
    staticLabels:
      app: netobserv-flowcollector
